services:
  backend:
    build: ./Backend
    image: jagan395/calories_burnt_prediction:Backend
    container_name: calories_burnt_prediction_fastapi_app
    ports:
      - "8000:8000"

  frontend:
    build: ./Frontend
    image: jagan395/calories_burnt_prediction:Frontend
    container_name: calories_burnt_prediction_streamlit_app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/predict
    depends_on:
      - backend